### ISSUE TITLE
Nasty traceback when input BAM is unsorted

### ISSUE THREAD

**Issue by jfy133** [maxibor/bamAlignCleaner#1]
On v0.2

```
$ bamAlignCleaner JK2802_T1.bam 
[E::idx_find_and_load] Could not retrieve index file for 'JK2802_T1.bam'
[WARNING]: Indexing JK2802_T1.bam
[E::hts_idx_push] Unsorted positions on sequence #3: 8510 followed by 2180
[E::sam_index] Read 'AHSTEUER006:166:C5UJMANXX:8:1101:16952:2276' with ref_name='NC_007596.2', ref_length=16770, flags=16, pos=2180 cannot be indexed
Traceback (most recent call last):
  File "/home/jfellows/.conda/envs/bamAlignCleaner/lib/python3.7/site-packages/bamaligncleaner/main.py", line 41, in filter_bam
    alignment.check_index()
  File "pysam/libcalignmentfile.pyx", line 773, in pysam.libcalignmentfile.AlignmentFile.check_index
ValueError: mapping information not recorded in index or index not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jfellows/.conda/envs/bamAlignCleaner/bin/bamAlignCleaner", line 10, in <module>
    sys.exit(cli())
  File "/home/jfellows/.conda/envs/bamAlignCleaner/lib/python3.7/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/jfellows/.conda/envs/bamAlignCleaner/lib/python3.7/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/jfellows/.conda/envs/bamAlignCleaner/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jfellows/.conda/envs/bamAlignCleaner/lib/python3.7/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/jfellows/.conda/envs/bamAlignCleaner/lib/python3.7/site-packages/bamaligncleaner/cli.py", line 34, in cli
    filter_bam(bam, method, output)
  File "/home/jfellows/.conda/envs/bamAlignCleaner/lib/python3.7/site-packages/bamaligncleaner/main.py", line 44, in filter_bam
    index = bam_index(bam, filetype)
  File "/home/jfellows/.conda/envs/bamAlignCleaner/lib/python3.7/site-packages/bamaligncleaner/main.py", line 17, in bam_index
    pysam.index(alignment)
  File "/home/jfellows/.conda/envs/bamAlignCleaner/lib/python3.7/site-packages/pysam/utils.py", line 75, in __call__
    stderr))
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: failed to create index for "JK2802_T1.bam"\n'
```

**Comment by maxibor** [comment]
Could you upload/point me to the `JK2802_T1.bam` unsorted `bam` file for testing ? @jfy133 f

**Comment by jfy133** [comment]
[JK2782_T1.bam.log](https://github.com/maxibor/bamAlignCleaner/files/6960935/JK2782_T1.bam.log)

Remove `.log`

**Comment by maxibor** [comment]
Thanks @jfy133 
I've added checkpoints and made the traceback easier to follow with 2620b98
